/*
 * generated by Xtext 2.31.0
 */
package uk.kcl.inf.mdd1.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import uk.kcl.inf.mdd1.turtles.TurtleProgram

@ExtendWith(InjectionExtension)
@InjectWith(TurtlesInjectorProvider)
class TurtlesParsingTest {
	@Inject
	ParseHelper<TurtleProgram> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
