/*
 * generated by Xtext 2.31.0
 */
package uk.kcl.inf.mdd1.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.kcl.inf.mdd1.TurtlesRuntimeModule;
import uk.kcl.inf.mdd1.TurtlesStandaloneSetup;
import uk.kcl.inf.mdd1.ide.TurtlesIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class TurtlesWebSetup extends TurtlesStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TurtlesRuntimeModule(), new TurtlesIdeModule(), new TurtlesWebModule()));
	}
	
}
