/*
 * generated by Xtext 2.31.0
 */
package uk.kcl.inf.mdd1.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class TurtlesWebModule extends AbstractTurtlesWebModule {
}
