/*
 * generated by Xtext 2.31.0
 */
package uk.kcl.inf.mdd1;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TurtlesStandaloneSetup extends TurtlesStandaloneSetupGenerated {

	public static void doSetup() {
		new TurtlesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
