/*
 * generated by Xtext 2.31.0
 */
package uk.kcl.inf.mdd1;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TurtlesRuntimeModule extends AbstractTurtlesRuntimeModule {
}
