/*
 * generated by Xtext 2.31.0
 */
package uk.kcl.inf.mdd1.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class TurtlesProposalProvider extends AbstractTurtlesProposalProvider {
}
